_target_: src.models.image_text_mask_module.ImageTextMaskModule

net:
  _target_: src.models.core_models.trans_segmentor.TransformerSegmentor
  image_pretrained_model_name_or_path: ${image_pretrained_path}
  text_pretrained_model_name_or_path: ${text_pretrained_path}
  freeze_image_encoder: false
  freeze_text_encoder: false
  add_pos_enc: false
  decoder_layer_kwargs:
    nhead: 8
    dropout: 0.1
    norm_first: true
  num_decoder_layers: 4
  num_upsampler_layers: 5
  num_output_channels: 1

loss_fn:
  _target_: monai.losses.DiceCELoss
  sigmoid: true
  lambda_ce: 0.25

weight_decay: 0.0
optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 2.0e-5

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 5

tokenizer_name_or_path: ${tokenizer_pretrained_path}

# compile model for faster training with pytorch 2.0
compile: false

task: binary
threshold: 0.5
