defaults:
  - model_checkpoint
  - early_stopping
  - model_summary
  - rich_progress_bar
  - _self_

monitor: val_dice

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}"
  monitor: ${monitor}
  mode: max
  save_last: true
  auto_insert_metric_name: true

early_stopping:
  monitor: ${monitor}
  patience: 10
  mode: "max"

model_summary:
  max_depth: -1
