defaults:
  - model_checkpoint
  - early_stopping
  - model_summary
  - rich_progress_bar
  - lr_monitor
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}"
  monitor: val_dice
  mode: max
  save_last: true
  auto_insert_metric_name: true

early_stopping:
  monitor: val_loss
  patience: 12
  min_delta: 0.0001
  mode: "min"

model_summary:
  max_depth: 4
