# @package _global_

defaults:
  - _self_
  - data: mnist # choose datamodule with `test_dataloader()` for evaluation
  - model: mnist
  - callbacks: null
  - logger: null
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default

  # experiment configs allow for version control of specific hyperparameters
  # e.g. best hyperparameters for given model and datamodule
  - experiment: ??

task_name: "eval"

tags: ["dev"]

testing: true

# predict on test set, using best model weights achieved during training
# lightning chooses best weights based on the metric specified in checkpoint callback
predict: true

# passing checkpoint path is necessary for evaluation
ckpt_path: ???

# Disable empty ckpt check
disable_ckpt: false

# Default path for all of the datasets
data_root: ${paths.data_dir}

output_masks_dir: ${paths.output_dir}/output_masks
