# @package _global_

defaults:
  - _self_
  - data: mnist # choose datamodule with `test_dataloader()` for evaluation
  - model: mnist
  - logger: null
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default

task_name: "eval"

tags: ["dev"]

# predict on test set, using best model weights achieved during training
# lightning chooses best weights based on the metric specified in checkpoint callback
predict: true

# passing checkpoint path is necessary for evaluation
ckpt_path: ???
