# Copyright (c) OpenMMLab. All rights reserved.
from .backends import (
    BaseStorageBackend,
    HTTPBackend,
    LmdbBackend,
    LocalBackend,
    MemcachedBackend,
    PetrelBackend,
    register_backend,
)
from .file_client import FileClient, HardDiskBackend
from .handlers import (
    BaseFileHandler,
    JsonHandler,
    PickleHandler,
    YamlHandler,
    register_handler,
)
from .io import (
    copy_if_symlink_fails,
    copyfile,
    copyfile_from_local,
    copyfile_to_local,
    copytree,
    copytree_from_local,
    copytree_to_local,
    dump,
    exists,
    generate_presigned_url,
    get,
    get_file_backend,
    get_local_path,
    get_text,
    isdir,
    isfile,
    join_path,
    list_dir_or_file,
    load,
    put,
    put_text,
    remove,
    rmtree,
)
from .parse import dict_from_file, list_from_file

__all__ = [
    "BaseFileHandler",
    "BaseStorageBackend",
    "FileClient",
    "HTTPBackend",
    "HardDiskBackend",
    "JsonHandler",
    "LmdbBackend",
    "LocalBackend",
    "MemcachedBackend",
    "PetrelBackend",
    "PickleHandler",
    "YamlHandler",
    "copy_if_symlink_fails",
    "copyfile",
    "copyfile_from_local",
    "copyfile_to_local",
    "copytree",
    "copytree_from_local",
    "copytree_to_local",
    "dict_from_file",
    "dump",
    "exists",
    "generate_presigned_url",
    "get",
    "get_file_backend",
    "get_local_path",
    "get_text",
    "isdir",
    "isfile",
    "join_path",
    "list_dir_or_file",
    "list_from_file",
    "load",
    "put",
    "put_text",
    "register_backend",
    "register_handler",
    "remove",
    "rmtree",
]
